### PR TITLE
 build: Use libxkbcommon to resolve keysyms 

### PR DESCRIPTION
**Pull request by ueno**
Although it's still a bit ugly, this implements what I outlined in:
https://github.com/ueno/libskk/pull/47#pullrequestreview-90426727

### CODE REVIEW

**Comment by ueno** [comment]
@lo48576 would you like to review this?

**Comment by lo48576** [comment]
Thanks, I'll try this patch soon (tomorrow if possible).

**Comment by ueno** [comment]
Thank you!

**Comment by lo48576** [comment]
With this patch (and fcitx-skk), Control key is wrongrly handled.
(Shift key seems to behave as same, so I think there is an issue around modifier key handling.)

1. Ctrl key confirms preedit
input: `A o SPC Control_L` (not at `skk` command, in real world)
expected: `▼青` (not confirmed)
got: `青` (confirmed)

2. Ctrl key removes incomplete alphabet at hiragana mode
input: `H o h Control_L` (in real world)
expected: `▽ほh` (not confirmed)
got: `ほ` (confirmed)

**Comment by ueno** [comment]
Thank you for testing; let's merge it then.

**Pull request merged**
